name: Frontend Docker CI

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t jeyakumar56/mmt-frontend:latest .

      - name: Push Docker Image
        run: docker push jeyakumar56/mmt-frontend:latest

      - name: Deploy Frontend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/mmt-app
            docker compose pull frontend
            docker compose up -d frontend